import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar'
import Footer from './components/Footer'
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CariMentor',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="{inter.className} overflow-x-hidden" >
        <NavBar></NavBar>
        {children}
        <Footer></Footer>
        <SpeedInsights></SpeedInsights>
        </body>
    </html>
  )
}
